### PR TITLE
Adding PSOL CAD and updating assembly docs

### LINKED ISSUE #922: Document integration of oxygen PSOL
**Folder/Page:**
https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/oxygen

**Task:**
Identify selection of proportional solenoid for oxygen control
Document interfacing the PSOL with:
- pneumatic/tubing system
- electrical system
- mechanical fastening to frame
- provide CAD model for mechanical engineering team

### PR DESCRIPTION
**Pull request by martukas**
* Added CAD for
  * SMC PSOL
  * Uflow PSOL
  * BSPT and NTP fittings
* Detailed BOM for PSOL assembly
* More detailed explanation of PSOL installation on Oxygen page

Closes #922

### CODE REVIEW

**Comment by inceptionev** [comment]
Documentation updates and inventor parts look correct, however, the 5894K34 1/4" ID Tygon tubing is rated for 5psi max and should not be used at the oxygen inlet pressure nor the intermediate regulated pressure.  It could be used at the patient inhale limb pressure but since these hoses would be easy to mix up, whatever solution used would probably be best applied to all the entire oxygen inlet pathway unless it would be impossible to mix up.

One possible solution: use PU push-to-connect pneumatic fittings (ex: 5225K713) and tubing (ex: 50315K24) from the oxygen inlet to the regulator and from the regulator to the PSOL.  It possible that the PU hose can be used from the PSOL to the inhale limb as well but I'm not sure if we would run into flow constriction problems at the lower pressure of the inlet limb.  Any pneumatics people want to chime in here?

**Comment by martukas** [comment]
@inceptionev this seems like it might be a separate ticket? The Tygon stuff has been in there for a while and I have not touched it this PR.

**Comment by inceptionev** [comment]
sounds good, I'll approve this PR and make another ticket.

**Review by inceptionev — APPROVED** [review]

**Comment by martukas** [comment]
The new ticket for Tygon issue is #996

**Pull request merged**
