### PR TITLE
Enclosure redesign and (moderate) manufacturing documentation changes

### LINKED ISSUE #957: Equipment tray and enclosure modifications for v0.4
**What has to be done**
This is an umbrella ticket encompassing all modifications needed to the main equipment tray and enclosure.

This basically encompasses everything in the [v.4 enclosure milestone](https://github.com/RespiraWorks/Ventilator/milestone/27)

**Definition of "done"**
The following must be satisfied:
* consensus reached on the tray design being adequate to accommodate all potential components in the 0.4 iteration.
* CAD files for bent sheet metal must be finalized for submission to manufacturer

**How do you know it has to be done**
v0.3 enclosed build had problems
each linked sub-issue should trace back to build feedback notes

**Code pointers**
pinned notes in #eng-mechanical

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

### LINKED ISSUE #1099: Finalize drawings for enclosure
**What has to be done**
We need drawings for all v0.4 enclosure components and sub-assemblies such as have to be ordered from contract manufacturer.

**Needed:**
* [x] Drawings of sheet metal parts
* [ ] Drawings of sub-assemblies with PEM nuts

**What we DON'T need**
* JPGs or thumbnails of the drawings for the markdown pages
* assembly drawings or instructions of the whole enclosure with internals or acrylics, etc..
* any exported BOM files

**How do you know it has to be done**
Because we need to order the parts.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

### LINKED ISSUE #1160: New renderings for 0.4 enclosure
**What has to be done**
Need renderings of the enclosure components for the markdown pages documenting the parts:

Depicted components of the enclosure assembly be the sub-assemblies with PEM nuts, but not necessarily with acrylics. The display panel and filter panel can have acrylics, but the main pneumatics tray and the rear panel don't need to be there, because they are not finalized. Components should be shown so they can be conceptually understood by anyone reading about our design.

The totality of the ventilator with enclosure should also be depicted. 

Try to aim for high quality images, especially for full enclosure depiction:
* at a nice angle
* with shadows
* with reflections
* realistic perspective
* ray tracing on

More info about graphics standard in the wiki:
* https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide
* https://github.com/RespiraWorks/Ventilator/wiki/Mechanical-engineering-notes

**How do you know it has to be done**
New renderings are needed to update and publish the github pages, so that contributors in various geographic locations understand the vision of what we are creating, know what to manufacture, what it should appear like when they receive it.

**Starting points**
See the pages for the v0.3 enclosure and aim for same or better quality.

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

### LINKED ISSUE #1161: Update 1 to the enclosure documentation pages
**What has to be done**
All the markdown pages should be updated for the new tray(s) and enclosure assemblies to reference and link:
* new inventor files
* new renderings
* new drawings
* new parts

**What this is NOT**
We do not need detailed assembly instructions. This will be done after we get to build a few of these and can confim how it is done, and that will be capctured ticket .... TODO

**Subtasks:**
* [ ] Add subtasks or sections of content if applicable
* [ ] Identify documentation that should be updated upon completion

**How do you know it has to be done**
Link any documents, Slack threads, quote personal communication, reference your personal domain expertise etc. explaining why you think this should be done.

Link to requirements or risk analysis if applicable.

**Starting points**
Dependencies: #1160 #1099

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

### PR DESCRIPTION
**Pull request by martukas**
# Description

This is a redesign of the enclosure, equipment tray, and other sub-panel support structures, such as acrylic plates and mounting solutions. This redesign has huge knock-on effects on various other subsystems. As a result, the main pneumatics sub-assembly has become obsolete and thus was removed. Many of the assembly instructions and other integration notes will have to be rewritten when we get to test-building and redesigning those subsystems.

Some drawings and other outputs have been updated. Many drawings (especially assembly drawings) are missing. Outputs have been migrated to Google Drive to curb repository bloat. Only Inventor files crucial to the evolving design remain in the repository, as well as the associated `idw` drawing files, but none of their PDF or STL or STEP exports.

Some documentation has been updated on a best-effort basis. There are no broken links, but BOMs have no claim to being complete. Some prices have been eyeballed and so noted with `~` on a best effort basis.

Internals assembly instructions remain as they were before, just so there is at least some guide/template for when we have to redo it.

Closes #957
Closes #1099 
Closes #1160 
Closes #1161 

# General checklist:

- [x] I have performed a self-review, including - looked through the `Files changed` tab, browsed repository in my branch
- [x] I have made corresponding changes to the documentation - to reflect changes in code, electrical or mechanical design
- [x] All new documentation or graphics follow the [documentation style guide](https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide)
- [x] All new content is linked, easily discoverable, does not require too many clicks
- [x] I have reviewed any other relevant parts of our [contributor wiki](https://github.com/RespiraWorks/Ventilator/wiki) to ensure that this PR conforms to the standards
- [x] I have given the PR a descriptive name (prefixed with **WIP** if it is not yet ready for review)
- [x] I have tagged relevant reviewers

### CODE REVIEW

**Comment by inceptionev** [comment]
Feedback from Xometey (contract manufacturer):

```
Line item 4 (20220411-RW-Venti…tom-SHEETONLY-STEP) is a corrupted file. Please confirm the file is a single solid body, has no missing or corrupt surfaces and send over a revised file to me.

Also, we will need the left hand side CAD model.
```

**Review by inceptionev — COMMENTED** [review]
- [ ] Reviewed all changed READMEs
- [ ] Checked links to Google Drive
- [ ] Checked photos show up correctly
- [ ] Checked 3D models
- [ ] Checked drawings

Things to check:
- [ ] internals/blower/ still has an exports folder.  Is this desired?

**Review by inceptionev — APPROVED** [review]
Review complete, approved.  @martukas request to check on the export folder in the previous comment, but this is minor, so approving now.

**Review by inceptionev — CHANGES_REQUESTED** [review]
Found a potential problem.  When opening ventilator.iam, it seems some of the cooling fan links are broken, as well as global_params.ipt.  @martukas can you check this?

**Comment by martukas** [comment]
`blower/exports` was indeed "obsolete" if going by new organizational schema. I have moved the drawings out to main directory and images to `images`. More could be improved but the page is due for a more serious overhaul anyways when the Utah students finish with the new design.

Cooling fan coordinate system was not grounded. That was the only problem I could see with that sub-assembly. I'd try to clone and switch branches again to test if that loads correctly.

**Review by inceptionev — APPROVED** [review]
Did git reset and pull, .iam files load correctly now, thanks for your help @martukas

**Pull request merged**
