### PR TITLE
Wire fiO2 in placeholder inside GUI

### PR DESCRIPTION
**Pull request by asmodai27**
Needs testing as I don't have the hardware for now.

### CODE REVIEW

**Comment by inceptionev** [comment]
Built both controller and GUI from this branch and tested on pizza board SN 01.  There seems to be a display issue with the TV and FiO2 values running over each other.  I can confirm that the other live data (pressure/flow) seem to be coming through to the GUI fine though.

**Comment by inceptionev** [comment]
![Uploading 90308755...]

**Comment by inceptionev** [comment]
image

**Comment by asmodai27** [comment]
Hum... I expect we don't need better than 1% precision with this display, commit on its way.

**Comment by inceptionev** [comment]
yeah 1% resolution is good

**Comment by inceptionev** [comment]
Tested update on controller and GUI and it works.  Display responds to live changes in O2 concentration in system, and displays without decimal.  Note that without the high end calibration the 100% end is off (hence the 106% here) but what we are testing here is the GUI live data display and this is working correctly.

Good to merge PR

image

image

**Pull request merged**
