### PR TITLE
adding system monitor ADC

### PR DESCRIPTION
**Pull request by inceptionev**
continuation of #948, please see #948 for discussion

### CODE REVIEW

**Comment by inceptionev** [comment]
changed Do Not Populate parameter name to DNP and cleaned up net names, this is now ready for approval

**Comment by dcstraney** [comment]
Changed some small nitpick-y stuff; I'm onboard to commit if you're fine with those.

**Comment by inceptionev** [comment]
Cool, thanks.  Can you describe what changed?

**Comment by dcstraney** [comment]
Made the power ports inputs instead of outputs, and changed the symbol and library references for the ADC to point to the RespiraWorks library (I pushed some changes to the library as well).  That should be it.

**Comment by inceptionev** [comment]
Looks great, thanks @dcstraney, thanks!

**Review by dcstraney — APPROVED** [review]
Woohoo here we go

**Pull request merged**
