### PR TITLE
Instructions to run unit tests for debug interface locally

### PR DESCRIPTION
**Pull request by a-vinod**
# Description

Summary of changes
Added instructions to run unit tests locally for the debug interface.

Relevant motivation and context
Developing the interface and adding new unit tests require running unit tests locally.

Dependencies that are required for this change
None

## Self-review checklist:

- [x] Self-review: looked through the `Files changed` tab, browsed repository in branch
- [x] Documentation updated - reflects changes in code, electrical or mechanical design
- [x] Documentation and graphics follow the [documentation style guide](https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide)
- [x] New content is linked, easily discoverable, does not require too many clicks
- [x] Follows other relevant parts of [contributor wiki](https://github.com/RespiraWorks/Ventilator/wiki)
- [x] PR has a descriptive name
- [x] Tagged relevant reviewers

### Software only:

- [x] Follows our [code style](https://github.com/RespiraWorks/Ventilator/wiki/Code-style)
- [x] Commented code, particularly in hard-to-understand areas
- [x] All tests pass - new and old, locally and on CI
- [x] No new warnings or static check failures
- [x] Tests that prove fix is effective or new feature works
- [x] Manual tests are explained, with instructions for reproducing them

### CODE REVIEW

**Review by martukas — CHANGES_REQUESTED** [review]
So, on my machine the pip package does not seem to do the trick. Shell cannot find pytest. I had to install `pythonę-pytest` via apt. This could get us into a tailspin of what works on what distros, so maybe we could add an additional step to CircleCi jobs to just have a canonical way of this that works?

**Comment by a-vinod** [comment]
pytest is in the list of Python dependencies installed with 'controller.sh install' so there shouldn't be a need to install it via apt also. There's currently a circle ci step to run the these unit tests that runs pytest after installing the dependencies using 'controller.Sh install'

Did you check if pytest was already in the list of installed packages before installing it via apt? I.e. was this an issue with Bash not recognizing the pytest command or a missing dependency?

**Review by martukas — APPROVED** [review]
Ok, I have confirmed this to work on the ubuntu test machine at our workshop in Oakland. That's what really matters, so this is perfect. Thanks!

**Comment by a-vinod** [comment]
To minimize manual Python package installation and management, I removed the instruction I initially wrote to install pytest manually and pointed the reader to the controller.sh script where all packages are installed automatically

**Pull request merged**
