### PR TITLE
Technical drawings for v0.4 enclosure

### LINKED ISSUE #1099: Finalize drawings for enclosure
**What has to be done**
We need drawings for all v0.4 enclosure components and sub-assemblies such as have to be ordered from contract manufacturer.

**Needed:**
* [x] Drawings of sheet metal parts
* [ ] Drawings of sub-assemblies with PEM nuts

**What we DON'T need**
* JPGs or thumbnails of the drawings for the markdown pages
* assembly drawings or instructions of the whole enclosure with internals or acrylics, etc..
* any exported BOM files

**How do you know it has to be done**
Because we need to order the parts.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

### PR DESCRIPTION
**Pull request by gokcemay**
# Description

Added PDF files for technical drawings of parts. Missing assembly technical drawings. 

Closes #1099 

# General checklist:

- [x] I have performed a self-review, including - looked through the `Files changed` tab, browsed repository in my branch
- [ ] I have made corresponding changes to the documentation - to reflect changes in code, electrical or mechanical design
- [x] All new documentation or graphics follow the [documentation style guide](https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide)
- [ ] All new content is linked, easily discoverable, does not require too many clicks
- [ ] I have reviewed any other relevant parts of our [contributor wiki](https://github.com/RespiraWorks/Ventilator/wiki) to ensure that this PR conforms to the standards
- [x] I have given the PR a descriptive name (prefixed with **WIP** if it is not yet ready for review)
- [ ] I have tagged relevant reviewers

### CODE REVIEW

**Review by martukas — CHANGES_REQUESTED** [review]
* `bottom` lacks assembly drawing with PEM nuts
* `equipment bracket` lacks sheet metal drawing, we only have the assembly
* shouldn't `front` have an assembly? Hard for me to check without model, but it looks like it probably has PEM nuts?
* looks like names names of `electronics_support_frame` and its corresponding assembly are swapped
* it is `side_left` but `side_assembly` small thing, but maybe follow the same pattern and have `side_left_assembly`?
* seems we don't have corresponding `IDW` files for all the `PDFs`

**Comment by gokcemay** [comment]
- equipment bracket lacks sheet metal drawing, we only have the assembly

Added unfolded drawing as well. Was that what you asked for?

- bottom lacks assembly drawing with PEM nuts

Done

- Shouldn't front have an assembly? Hard for me to check without model, but it looks like it probably has PEM nuts?

Front isn't an assembly there are no PEM nuts or other parts.

- looks like names names of electronics_support_frame and its corresponding assembly are swapped

Corrected

- it is side_left but side_assembly small thing, but maybe follow the same pattern and have side_left_assembly?

Done

- seems we don't have corresponding IDW files for all the PDFs

Which PDF's are missing IDW? Can't find it.

**Review by martukas — CHANGES_REQUESTED** [review]
You can self-review by going to the "Files changed" tab of the Github PR interface and then doing `ctrl+F` to find names of files.

For example if you look for "back", it will highlight "back.pdf" and "back_panel_acrylic.pdf", but these are the only ones, there is no `idw` with the word "back", so it either does not exist of is mis-titled.

For another example "bottom" shows me only `bottom.pdf` and `bottom_assembly.pdf` but only `bottom_assembly.idw`. Does this IDW contain both those drawings that were just exported separately? I do not have Inventor, so I cannot check this.

I may point out more of these explicitly below, but you should self-check them all for completeness.

Other things I still am noticing:
* we now have PDF+IDW pairs of both `side_assembly` and `side_left_assembly`. Isn't that kind of redundant?
* Unlike for side assemblies, we only have unfolded one drawing for the unfolded sheet metal `side_left`, but not for its mirror on the right side. 
* Also, `side_assembly` points to all 3 PEM nuts and has handle+fan made invisible, whereas the `side_left_assembly` shows all components but only points to one PEM nut.
* `display_support_frame` has sheet metal drawing, but no assembly with PEM nuts. Also no IDWs.
* `equipment_bracket_assembly` does not point out to all the PEM nuts, and the descriptor for item 3 is not so clear. How is it different from the other PEM nut?
* `equipment_bracket_flat` and `equipment_bracket_part` appear to be just different views but delivering the same information? Do we need both?

**Comment by inceptionev** [comment]
Review notes:

- [ ] handle cutout on side_left is not grounded by dimension to the rest of the drawing
- [ ] center tab in top view does not appear to be rounded
- [ ] display support frame seems to be shown flat (not folded) in drawing

**Comment by martukas** [comment]
PDF outputs for manufacturing quote are being stored [here](https://drive.google.com/drive/folders/1Mv6GbDYOWyP9wygJNnGJ1-Wm2pC7y0ps?usp=sharing).

In previous comment @inceptionev refers to "center tab in top view" is for `side_left.pdf`

**Comment by inceptionev** [comment]
We made the decision to manufacture the outer enclosure in aluminum, which does not typically come in the same gauge thicknesses as steel.  Rather than 18ga stainless steel, the other enclosure will be 0.050" powder-coated aluminum.  We may need to alter the dimensions to accommodate this.

The internal frame components will still be 16ga steel.

**Review by martukas — APPROVED** [review]
Good enough for sending to manufacturing. Additional documentation- and presentation-related changes will be done in other PRs.

**Pull request merged**
