### PR TITLE
v0.3 Enclosure migration

### LINKED ISSUE #943: Migrate Enclosure components to Inventor
**What has to be done**
The enclosure needs to be migrated to Inventor. New parts and assemblies for the same must be created. 

A successful migration to Inventor must take place as is.

**How do you know it has to be done**
Currently only drawings are available here. Mass migration to Inventor is underway.

The following shall be created for all the components of the enclosure:

Inventor Solid Model
Engineering Drawing (both .idw and exported PDF)
Dxf file (For laser cutting)

Additionally, an assembly must also be created.

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

### PR DESCRIPTION
**Pull request by KishanKoradiya**
- Following files pertaining to the enclosure were added:
    - Ventilator enclosure (.ipt sheet metal file) 
       _**Note**: Minor dimensional inaccuracies (due to improper documentation) still persist; resultantly, some holes don't line up and gaps between folded panels may exist_
    - Ventilator closure panel (.ipt sheet metal file, .stl file, .dwg & .pdf drawings)
    - Equipment bracket (.ipt sheet metal file)
 
- Work ongoing to improve design to address issues brought up in engineering meetings (i.e. interfering screws when mounting pneumatics tray, better PCB mounting solution, preferably on acrylic as opposed to the display panel etc.)

Note: Contains parts from Inventor Content Center

closes #943

### CODE REVIEW

**Review by martukas — CHANGES_REQUESTED** [review]
* Equipment bracket: sketches, faces, holes are not named, over a 100 parameters are not descriptively named. Looking at the main sketches it has hard to tell how and why things have been dimensioned as they are. Makes me suspect that this could actually be done cleaner and in a more parametric way, using more symmetries and mathematical relations. Could it be the sketch was just brute-force imported?
* Enclosure: similar problems, in nature and in magnitude, particularly the parameters not being named makes it hard to review.
* Closure panel: similar problems, though less pronounced since the part is much less complex.
* Enclosure assembly:
  * lack of PEM nuts that are necessary to attach metal components together where bolts are to be used
  * No differentiation between rivets and screws.
  * The "bolt" stand-in component is not resolved after file was renamed, causing many warnings when loading.
  * There is a weird gap at the back, seems the closure panel is not snugly aligned in assembly (screenshot included)
  * There closure panel appears to be attached below the screw tabs, not above as it should be (screenshot included)
  * bolts meant to secure front acrylic panels to the equipment bracket appear to penetrate the entire assembly, which is not what is intended
* The `manufacturing/enclosed_build/enclosure/images/` path is not logical for these components, it should be identified as CAD
*  The PR includes a "Shelf acrylic" component under `manufacturing/enclosed_build/pneumatics/CAD` which is not in the scope of this PR

**Comment by martukas** [comment]
The gap:
image

Goes under tab, when it should go above:
image

**Comment by tijanim** [comment]
@KishanKoradiya and @martukas 

I looked thru the enclosure CAD with Martin's feedback in mind. Here are my thoughts: 

> * Equipment bracket: sketches, faces, holes are not named, over a 100 parameters are not descriptively named. Looking at the main sketches it has hard to tell how and why things have been dimensioned as they are. Makes me suspect that this could actually be done cleaner and in a more parametric way, using more symmetries and mathematical relations. Could it be the sketch was just brute-force imported?
This is not typical in CAD unless we have bespoke configurations. It is neater, but adds a lot of complexity and is confusing for newer users. It also makes quick edits much more challenging. I recommend we don't do this on single-config parts.

> * Enclosure: similar problems, in nature and in magnitude, particularly the parameters not being named makes it hard to review.
See above.
> * Closure panel: similar problems, though less pronounced since the part is much less complex.
See above
> * Enclosure assembly:
>   
>   * lack of PEM nuts that are necessary to attach metal components together where bolts are to be used
You're referring tot he other PEM nuts correct? Not the ones for the faceplate.
>   * No differentiation between rivets and screws.
Done in drawing, not model. Kishan, add an LOM in the  drawing, please
>   * The "bolt" stand-in component is not resolved after file was renamed, causing many warnings when loading.
Didn't load for me either. I reccommend saving the bolt part in the DAC folder alongside these parts and referencing that one.
>   * There is a weird gap at the back, seems the closure panel is not snugly aligned in assembly (screenshot included)
Agreed, this wasn't there in previous revisions. Please fix
>   * There closure panel appears to be attached below the screw tabs, not above as it should be (screenshot included)
Agreed, please fix.
>   * bolts meant to secure front acrylic panels to the equipment bracket appear to penetrate the entire assembly, which is not what is intended
Where are you seeing this? When I look right now that isnt the case. 
> * The `manufacturing/enclosed_build/enclosure/images/` path is not logical for these components, it should be identified as CAD
> * The PR includes a "Shelf acrylic" component under `manufacturing/enclosed_build/pneumatics/CAD` which is not in the scope of this PR
The changes to the enclosure affected the tray as well (hole placement). That's why they're in this PR. It makes sense to tackle all the sheet metal parts at once.

**Comment by KishanKoradiya** [comment]
@martukas @tijanim 

Suggested changes were made and following changes incorporated

- PEM nut like placeholder models added
- Rivets will have stand in components it seems. Screws and nuts are fine. I haven't figured out a way around this. A separate component for the rivet is always added to the corresponding folder; not so for the screws
- Gap eliminated
- Folded tab is now below. Closure panel is now above. As expected.
- No bolts are penetrating the assembly anywhere
- Separate CAD folder created. all relevant files moved there.
- Readme now reflects some info about where heat insert dimensions were taken from.

**Review by martukas — COMMENTED** [review]
* Only rivets hold the main enclosure together, prior to attachment of tray and closure
* Screws for attaching tray and closure should all be ISO 7380-1, M4, 12mm long
* Turns out Inventor has PEM nuts, the exact ones specified in our old BOM spreadsheet. Search Content center for "CLS", chose "metric" and then the two types we need are:
  * CLS-M6-1 for the rubber feet
  * CLS-M4-0 for all fasteners holding the enclosure together
* There appear to be unnecessary PEMs for where the upper acrylic would attach. If we want stand-ins for the heat-set inserts, those should probably go in the acrylic sub-assembly first
* on a similar note, the screws for attaching the front acrylic plates probably don't need to be there
* There is a gap of about 5mm where the bottom of the closure meets the enclosure at the back. This is probably because of the bend radius of this sheet of metal, and it should be extended to help it close up more nicely:
image

* For feet one could use something I found under "features -> metric -> partial cone", but might want to reach out to @afarrington17  he might be able to hammer a custom piece out pretty quick?

**Comment by KishanKoradiya** [comment]
> Only rivets hold the main enclosure together, prior to attachment of tray and closure

There were two screws. Now all are rivets.

> Screws for attaching tray and closure should all be ISO 7380-1, M4, 12mm long

Model updated to match this specification.

> Turns out Inventor has PEM nuts, the exact ones specified in our old BOM spreadsheet. Search Content center for "CLS", chose "metric" and then the two types we need are:
> 
> CLS-M6-1 for the rubber feet
> CLS-M4-0 for all fasteners holding the enclosure together

Thanks! Model updated to match this specification.

> There appear to be unnecessary PEMs for where the upper acrylic would attach. If we want stand-ins for the heat-set inserts, those should probably go in the acrylic sub-assembly first

> on a similar note, the screws for attaching the front acrylic plates probably don't need to be there

You're right. They belong in the face-plate sub-assembly. Removed all front acrylic mounting screws and nuts.

> There is a gap of about 5mm where the bottom of the closure meets the enclosure at the back. 

Eliminated.

**Review by martukas — APPROVED** [review]
Looks good.
Loads relatively easy for both @martukas and @tijanim 

Will probably need to replace rubber feet and possibly some of the nuts, but we'll do that when we have a full assembly.

**Pull request merged**
