### PR TITLE
Update OS version in GUI readme file

### PR DESCRIPTION
**Pull request by asmodai27**
# Description

Update OS version in GUI readme file

# General checklist:

- [ ] I have performed a self-review, including - looked through the `Files changed` tab, browsed repository in my branch
- [ ] I have made corresponding changes to the documentation - to reflect changes in code, electrical or mechanical design
- [ ] All new documentation or graphics follow the [documentation style guide](https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide)
- [ ] All new content is linked, easily discoverable, does not require too many clicks
- [ ] I have reviewed any other relevant parts of our [contributor wiki](https://github.com/RespiraWorks/Ventilator/wiki) to ensure that this PR conforms to the standards
- [ ] I have given the PR a descriptive name (prefixed with **WIP** if it is not yet ready for review)
- [ ] I have tagged relevant reviewers

## Code checklist:

- [ ] All new code follows our [code style](https://github.com/RespiraWorks/Ventilator/wiki/Code-style)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have described tests I used to verify my changes, instructions for reproducing them and any relevant configuration details.
- [ ] I ran the unit test suite and verified that all tests pass - new and old, locally and on CI
- [ ] I performed a clean build and verified that there were no warnings
- [ ] I ran our static analysis tools and verified there were no warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] All source files have license headers

### CODE REVIEW

**Review by martukas — COMMENTED** [review]
Is this the `Desktop` version of the OS? It would probably not be useful to get the headless one for GUI purposes.

**Comment by asmodai27** [comment]
> Is this the `Desktop` version of the OS? It would probably not be useful to get the headless one for GUI purposes.

Yes it is, though it ends up as a dead link in CI... I changed the link to get the parent folder rather than the final file, should be obvious from context that one should download the .zip (or .torrent) file.

**Comment by martukas** [comment]
> > Is this the `Desktop` version of the OS? It would probably not be useful to get the headless one for GUI purposes.
> 
> Yes it is the desktop version, though it ends up as a dead link in CI... I changed the link to get the parent folder rather than the final file, should be obvious from context that one should download the .zip (or .torrent) file.

I would make it explicit that it is the Desktop version that should be downloaded, as I think it may be pretty easy to grab the headless one. Happened to me a couple of times.

**Review by martukas — APPROVED** [review]
LGTM

**Pull request merged**
