### PR TITLE
Pinch valve migration to Inventor, update to v2.0, adaptation for vent build 0.3

### LINKED ISSUE #941: Migrate Pinch Valve components to Inventor
**What has to be done**
The pinch valve components (bearing, base, rotor) need to be migrated to Inventor.

A successful migration to Inventor must take place as is.

**How do you know it has to be done**
The current models are .step files. Mass migration to Inventor is underway.

The following shall be created for all the components of the pinch valve:

Inventor Solid Model
Engineering Drawing (both .idw and exported PDF)
Dxf file (For laser cutting)

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

### PR DESCRIPTION
**Pull request by martukas**
* reimplemented CAD of all pinch valve components in Inventor
* all sketches parameterized and most constraints labeled and optimized for future modifications
* incorporates gusset supports for shelf
* rotor space in the base is tighter, for improved durability
* rotor is taller to better interface with 30mm axle bolt
* mounting screw spacing changed for improved assembly
* stop shelf distance from shaft is dictated by tube diameter and compression slack parameters
* highly parametrized for improved adaptability in the future
* Inventor assembly with hardware from content center
* mounting ears removed, bolt layout symmetrical, narrower base
* shaft to shelf distance parametrized with tube compression factor
* new renderings and STL exports, docs updated

closes #941

### CODE REVIEW

**Comment by inceptionev** [comment]
There seems to be a typo in this paragraph:

> Flexible tubing-based pinch valves were selected based on the requirements for quick response time,git ad and the ability to keep the gas pathway clean (a feature unique to pinch valves, as most other forms of actuated valves require passing the gas through the valve workings).

Otherwise the readme content looks good.  I'm in the process of printing the valves and will post results here.

**Comment by inceptionev** [comment]
A small chamfer here (photo attached) will make the part easier to separate from the build plate during 3D printing (provided they are printed in this orientation, which I prefer, because it keeps the stepper interface perfectly flat)
image

**Comment by martukas** [comment]
Additional tweaks made to make sure the geometry is essentially the same compared to the old valves:
* distance from NEMA shaft to bearing axle - identical
* distance from NEMA shaft to tubing shelf - off by 0.013mm
Everything else should be essentially the same

**Review by tijanim — APPROVED** [review]
Looks good, works well with acrylic tray, no issues on my end.

**Pull request merged**
